# Generated by Django 4.2 on 2023-04-22 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newstv', '0002_rename_id_channel_channel_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='channel',
            old_name='image',
            new_name='channel_image',
        ),
        migrations.RenameField(
            model_name='channel',
            old_name='name',
            new_name='channel_name',
        ),
        migrations.RenameField(
            model_name='channel',
            old_name='url',
            new_name='channel_url',
        ),
        migrations.RenameField(
            model_name='channel',
            old_name='date',
            new_name='created_date',
        ),
    ]
